// Don't forget the curly braces and commas!

export const FAQS = [
    {
        id: 0,
        question: "How long does it take to build a castle?",
        answer: `Average castle building time is two years. Fastest built solid stone tower was two weeks. Fastest built solid stone real castle was 15 months.\nMany factors influence the time it takes to build a castle. The most important factor may be the site where the castle is to be built. Since castles are usually built on unique land, it may be difficult to transport materials and labor to the site. Local building regulations can delay the start of a castle or even prevent the building of a castle. It is wise to check out the local planning office and ask a ton of questions before purchasing castle land. How much of the work do you want to do yourself? While you can save money as your own labor, you must have sufficient free time on your hands. Local seasonal weather trends influence castle building. A climate too cold can require boxing in the castle construction or working only in the summer months. Too hot weather can wear out the work crew or require shading of the construction site. Best to enclose the section of castle under construction to allow an unhindered construction pace. Heavy rain can wash away or damage the looks of mortar. A sudden freeze can ruin mortar and your days stonework. The size of your castle is directly proportional to the time it takes to build your castle. The amount of labor and money that you use is inversely proportional to the time it takes to build. Since today's castle building techniques still contain much of the hand crafting of the old days, you should plan to allow more time to build a castle than a traditional modern building. There are many more factors that affect building time, but the previously mentioned factors seem to pop up most often.\nPlan to spend twice as long building a castle when compared to building a common structure. For a small or medium sized castle, you should allow one to two years. For a large castle with inner and outer curtain walls, you should allow five years or increase the amount of labor and funds used. On the bright side, your castle will last for generations and increase in value over time.`,
    },
    {
        id: 1,
        question: "How much does it cost to build a castle?",
        answer: `As with the time it takes to build a castle, most of the same factors can affect the cost of a castle. The remoteness of the site, the weather, the supply and cost of materials and labor, the cost and time for building permits, and the selection of materials used can all affect the cost of your castle. For 2023, new castle construction costs ranged from $525/sq ft to $700/sq ft for a complete finished castle.\nDuring the past 49 years, we have observed government regulations on building escalate from simple fees and helpful inspections to one as a big source of revenue for local and state governments. This can now have a dramatic effect on the cost of your castle. If you are on a tight budget, head for one of the few remaining locations where government fees are lowest.`,
    },
    {
        id: 2,
        question: "How much does it cost to build a castle?",
        answer: `As with the time it takes to build a castle, most of the same factors can affect the cost of a castle. The remoteness of the site, the weather, the supply and cost of materials and labor, the cost and time for building permits, and the selection of materials used can all affect the cost of your castle. For 2023, new castle construction costs ranged from $525/sq ft to $700/sq ft for a complete finished castle.\nDuring the past 49 years, we have observed government regulations on building escalate from simple fees and helpful inspections to one as a big source of revenue for local and state governments. This can now have a dramatic effect on the cost of your castle. If you are on a tight budget, head for one of the few remaining locations where government fees are lowest.`,
    },
];